def handle_error(method, exception, traceback, send_mail=False):
	""" handle exception and save the log """
	pass